[msg arbeit_help_00]
[s]占位：打工帮助[n][w][e]

[msg arbeit_ok_00]
[s]打工帮助占位打工帮助占位[n][w][e]

[msg arbeit_disable_00]
[s]占位：打工帮助[n][w][e]

[msg arbeit_setted_00]
[s]占位：打工帮助[n][w][e]

[msg arbeit_help_01]
[s]占位：打工帮助[n][w][e]

[msg arbeit_under_help_combin]
[s]通过接待客人提升魅[n]力！时间：下午工资[n]：每日￥３５００以[n]上地点：涩谷中央大[n]街条件：无[n][w][e]

[msg arbeit_ok_combini [摩尔加纳]]
[s][bup 0 3 0 0 0]打工帮助占位打工帮助占位打工帮助占位[n][w][e]

[msg arbeit_disable_combini [摩尔加纳]]
[s][bup 0 3 0 0 0]占位：打工帮助[n][w][e]

[msg arbeit_setted_combini [摩尔加纳]]
[s][bup 0 3 0 0 0]占位：打工帮助[n][w][e]

[msg arbeit_under_help_flower [摩尔加纳]]
[s]学习关心他人！时[n]间：下午工资：每[n]日￥３２００以上[n]地点：涩谷地下商[n]场条件：令人瞩目[stIcon 1][clr 26][stLabel 1][clr 27][n][w][e]

[msg arbeit_ok_flower [摩尔加纳]]
[s][bup 0 3 0 0 0]打工帮助占位打工帮助占位打工帮助占位[n][w][e]

[msg arbeit_disable_flower [摩尔加纳]]
[s][bup 0 3 0 0 0]等等，上面写着需要「一定[n]程度的魅力」……我觉得你[n]还不够，做不了这个。[n][w][e]

[msg arbeit_setted_flower [摩尔加纳]]
[s][bup 0 3 0 0 0]占位：打工帮助[n][w][e]

[msg arbeit_under_help_gyudon [摩尔加纳]]
[s]提升灵巧！时间[n]：夜晚工资：￥[n]３６００以上地[n]点：涩谷中央大[n]街条件：无[n][w][e]

[msg arbeit_ok_gyudon [摩尔加纳]]
[s][bup 0 3 0 0 0]打工帮助占位打[n]工帮助占位在中[n]央大街。你知道[n]那在哪里吧，？[n][w][e]

[msg arbeit_disable_gyudon [摩尔加纳]]
[s]占位：打工帮助[n][w][e]

[msg arbeit_setted_gyudon [摩尔加纳]]
[s][bup 0 3 0 0 0]占位：打工帮助[n][w][e]

[msg arbeit_under_help_okama [摩尔加纳]]
[s]成为真正体贴的[n]人！时间：夜晚[n]工资：￥７２０[n]０地点：新宿条[n]件：面试决定[n][w][e]

[msg arbeit_ok_okama [摩尔加纳]]
[s][bup 0 3 0 0 0]打工帮助占位打工帮助占位[n][w][e]

[msg arbeit_disable_okama [摩尔加纳]]
[s]占位：打工帮助[n][w][e]

[msg arbeit_setted_okama [摩尔加纳]]
[s][bup 0 3 0 0 0]占位：打工帮助[n][w][e]
